version: "3.8"

services:
  server:
    container_name: oqm_server
    restart: unless-stopped
    image: oqm-server:1.0.0
    build:
      dockerfile: Dockerfile
      context: server
    ports:
      - 3001:3001

  client:
    container_name: oqm_client
    restart: unless-stopped
    image: oqm-client:1.0.0
    build:
      dockerfile: Dockerfile
      context: client/se2022-08-oqm
    ports:
      - 3000:3000
    depends_on:
      - server
